### ISSUE TITLE
cannot apply styles to text

### ISSUE THREAD

**Issue by ryandeussing** [swastik/en-editor#1]
In my app (and in the addon's dummy app) selecting text and applying styles via the toolbar has no effect. Thank for any tips to make this work!

**Comment by swastik** [comment]
Thanks for reporting, Ryan!

Are you seeing any errors on the console? Also: what browser is this?

**Comment by swastik** [comment]
Okay, I noticed the issue. Trix recently updated to use data-trix-* attributes instead of data-* which broke the toolbar.

I've fixed it now. Please try the 0.1.5 version and let me know if there are any issues!

**Comment by ryandeussing** [comment]
Thanks!
