### ISSUE TITLE
How change content dynamically 

### ISSUE THREAD

**Issue by brunowego** [swastik/en-editor#2]
You talk about a way to change the content dynamically, can you provide a example of this? Thanks.

**Comment by brunowego** [comment]
With help of @zamansaray.

```js
import Controller from 'ember-controller';

export default Controller.extend({
  element: null,

  actions: {
    load(id) {
      let template = this.get('store').peekRecord('template', id);

      this.get('element').innerHTML = template.get('body');
    },

    setElement(element) {
      this.set('element', element);
    }
  }
});
```

**Comment by swastik** [comment]
@brunowego Sorry, didn't get around to this earlier. 😃 

Yes, that is a good way of doing it. I had some issues with that in the past though — I'm not sure what they were, but we ended up going with Trix's `insertHTML` method. See: https://github.com/basecamp/trix#inserting-html

The idea is the same... you use the `onInit` action to store the editor on the parent component and then use `insertHTML`.
